name: bloc_structure_template
description: A template repository that provides a quick start for creating new Flutter apps using Bloc
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  dio: ^4.0.6
  get_it: ^7.2.0
  flutter_easyloading: ^3.0.5
  logger: ^1.1.0
  connectivity_plus:
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  injectable: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  get_storage: ^2.1.1
  shimmer: ^2.0.0
  top_snackbar_flutter: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  pretty_dio_logger: ^1.1.1
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1

flutter:

  uses-material-design: true
